### ISSUE TITLE
Unable to reopen closed tabs

### ISSUE THREAD

**Issue by joserebelo** [moneytoo/DontCloseWindowWithLastTab#3]
After you close one of the last two tabs, if you try to reopen tabs with CTRL+SHIFT+T you are only able to reopen the last one that you closed. After that, it tries to reopen the pinned tab which closes instantly.

Unsure if it is possible to solve this though, due to the current implementation.

**Comment by moneytoo** [comment]
As you correctly mention, it's not really possible to solve because of how the whole extension works with opening and closing of new tab pages. 
There's API for working with browser history but not the "Recently closed". 

There are some extensions with alternative approaches so you may want to try extensions like "Last Tab Keepalive" or "ReCreateWindow".

**Comment by joserebelo** [comment]
I still prefer this implementation, I can live without being able to reopen those last closed tabs.

Guess this issue can be closed, thanks for creating this extension :)
